import type { Setting } from "../types.ts";

export const sqlServerConnectionStringKey = "SQL_SERVER_CONNECTION_STRING";
export const sqlServerRemoveBackslashOnDatesKey =
  "SQL_SERVER_REMOVE_BACKSLASH_ON_DATES";

export const defaultSettings: Setting[] = [
  {
    setting_name: sqlServerConnectionStringKey,
    setting_description:
      "The connection string to use to connect to a SQL database.",
    setting_type: "Text",
    text_value: "",
  },
  {
    setting_name: sqlServerRemoveBackslashOnDatesKey,
    setting_description:
      "Whether or not to remove the backslash on date strings. This is normally needed for queries generated by some Gemini models.",
    setting_type: "Boolean",
    boolean_value: false,
  },
];
